# This is a basic workflow to help you get started with Actions

name: Unit tests under tests

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the github-action-setup branch
  pull_request:
    branches: [main, releases/*]
    paths-ignore:
      - "docs/**"
      - "experimental/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [unit, release]
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run tox unit tests
        run: |
          pip install tox
          tox -e py38-torch1110-${{ matrix.test }}
